#!/bin/env pwsh

#hooks run in the context of the repo root

$HookScriptFileName=""	#ie "pre-push.ps1"

$HookScriptLocation=(Get-Item ([string]::IsNullOrWhiteSpace($PSScriptRoot) ? (Get-Location).Path : $PSScriptRoot))
$HookScriptLocation=(Join-Path -Path $HookScriptLocation -ChildPath (Join-Path -Path "Git hooks" -ChildPath $HookScriptFileName))
$ReturnCode=(Invoke-Expression -Command "& '$HookScriptLocation'")

if ($ReturnCode -eq 0)
{
	Exit $ReturnCode
}
else
{
	Exit 1
}